### PR TITLE
V2 API and python3 support

### PR DESCRIPTION
**Pull request by Kronopt**
I had already done most of the job last year, as can be seen here #16.
I wanted to continue to push to the same pull request but I had already delete the fork and I couldn't find any other way to do it, so I opened this new pull request.

What I did was implement the whole pokeapi.co V2 API using [beckett](https://pypi.org/project/beckett/).
I also:

- Added support to python 3 (tested 3.6 and 3.7)
- Removed pre-beckett (legacy) code
- Added a fix to the beckett module
- Cleaned and updated requirements.txt
- Updated a great deal of documentation

tests passed for python 2.7, 3.7 and 3.6.
Pep8 is mostly ok.
flake8 and coverage are ok.

There's still the issue of the resourcesV2.ChainLinkSubResource not working properly.
The 'evolves_to' subresource is another ChainLinkSubResource, and I still have to figure out how to implement this functionality.

### CODE REVIEW

**Comment by Kronopt** [comment]
circleci is failing because tox can't find python 3.6 and 3.7 interpreters...
Tox passed ok on my machine.

**Comment by Naramsim** [comment]
you could try to change the circleci config to make the tests pass

**Comment by Naramsim** [comment]
Be aware that the supported python wrapper is now: https://github.com/GregHilmes/pokebase

**Comment by Kronopt** [comment]
Circleci is now configured correctly.

> Be aware that the supported python wrapper is now: https://github.com/GregHilmes/pokebase

Well, I've offered to support this in #17 and in [PokeAPI/pokeapi#350 (comment)](https://github.com/PokeAPI/pokeapi/issues/350#issuecomment-428037972), no one got back to me though.
I just went and updated it anyway.

**Comment by Naramsim** [comment]
Could you please highlight the difference of this package with respect to https://github.com/GregHilmes/pokebase?

I think one of those could be caching

**Comment by GregHilmes** [comment]
My documentation is mostly complete, I was only waiting on myself to finalize the next major release for pokebase, but I don't think I'll have the time to get to that soon. Also a user of my code noted that the current caching implementation is very slow, so I want to investigate that before release, but again, I don't have the time, as much as I really, really want to.

**Comment by Kronopt** [comment]
I also would like to point out that I'm still willing to maintain pykemon.
I'll continue to push changes to my fork and opening pull requests here, nonetheless.

**Comment by Naramsim** [comment]
We can just have two wrappers.

**Pull request merged**
