### PR TITLE
CI fixes

### PR DESCRIPTION
**Pull request by sargunster**
* Update Travis link in the readme
* Update the requirements.txt to fix the build
* Remove Python 2.6 from the tox file (you had already removed it from the travis file)

### CODE REVIEW

**Comment by phalt** [comment]
Looks like the pip requirements need to be updated?

**Comment by sargunster** [comment]
Yeah. I'm not sure exactly what change is needed there, I was just fixing the link.

**Comment by sargunster** [comment]
Looks like the build is fixed now!

**Comment by phalt** [comment]
Niceeee

**Pull request merged**
